# Generated by Django 5.2.7 on 2025-12-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFeatureMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('free', models.CharField(blank=True, max_length=50, null=True)),
                ('basic', models.CharField(blank=True, max_length=50, null=True)),
                ('pro', models.CharField(blank=True, max_length=50, null=True)),
                ('enterprise', models.CharField(blank=True, max_length=50, null=True)),
                ('data_type', models.CharField(default='boolean', max_length=20)),
            ],
            options={
                'db_table': 'subscription_feature_matrix',
                'managed': False,
            },
        ),
    ]
