# Generated by Django 5.2.7 on 2025-10-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('otp_code', models.CharField(max_length=6)),
                ('expiry_time', models.DateTimeField()),
            ],
        ),
    ]
