# Generated by Django 5.2.7 on 2025-11-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_department_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=10, unique=True)),
                ('error_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_code', models.CharField(max_length=10, unique=True)),
                ('information_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_code', models.CharField(max_length=10, unique=True)),
                ('validation_message', models.TextField()),
            ],
        ),
    ]
