# Generated by Django 5.2.7 on 2025-11-12 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usererror_userinformation_uservalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 chars or fewer.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usererror',
            name='error_message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='information_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uservalidation',
            name='validation_message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('role_name', 'department')},
        ),
    ]
