# Generated by Django 5.2.7 on 2025-11-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usererror',
            table='user_error',
        ),
        migrations.AlterModelTable(
            name='userinformation',
            table='user_information',
        ),
        migrations.AlterModelTable(
            name='uservalidation',
            table='user_validation',
        ),
    ]
