# Generated by Django 5.2.8 on 2025-11-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_permission_departmentpermission_rolepermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
