# Generated by Django 5.2.7 on 2025-12-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_tenant_user_is_superadmin_user_is_tenant_admin_and_more'),
        ('accounts', '0014_userprofile'),
    ]

    operations = [
    ]
